// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using xmas_stocking.DAL.Persistance;

#nullable disable

namespace xmas_stocking.DAL.Migrations
{
    [DbContext(typeof(XmasStockingDbContext))]
    partial class XmasStockingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("xmas_stocking.DAL.Persistance.Models.Attendee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredGifts")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Attendee");
                });

            modelBuilder.Entity("xmas_stocking.DAL.Persistance.Models.Draw", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfAttendees")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("draws", (string)null);
                });

            modelBuilder.Entity("xmas_stocking.DAL.Persistance.Models.Draw", b =>
                {
                    b.OwnsMany("xmas_stocking.DAL.Persistance.Models.GiftPresenter", "Attendees", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("GiftRecipientId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PreferredGifts")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("drawId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("GiftRecipientId");

                            b1.HasIndex("drawId");

                            b1.ToTable("attendees", (string)null);

                            b1.HasOne("xmas_stocking.DAL.Persistance.Models.Attendee", "GiftRecipient")
                                .WithMany()
                                .HasForeignKey("GiftRecipientId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("drawId");

                            b1.Navigation("GiftRecipient");
                        });

                    b.Navigation("Attendees");
                });
#pragma warning restore 612, 618
        }
    }
}
